# QuarkX Theme Configuration

# Menu
menu:
  Home: /
  Archive: /archives
  About: /about

# Logo text
logo: "Wayne Lex"

# Subtitle for typewriter effect
typewriter_texts:
  - "气质方面，我竟然该死的迷人。"
  - "打工？这辈子都不可能打工的。"
  - "失败我也见过，它对我挺客气的。"
  - "我不追风口，我就是风口。"
  - "你以为我在努力，其实我在升级。"
  - "成功这件事，我只是按流程走。"
  - "不是我想赢，是我不太会输。"



# Footer
footer:
  since: 2026
  powered_by: true

# Search
search:
  enable: true
  placeholder: "搜索关键字..."

# Code highlight
highlight:
  theme: minimal

# Social Links
social:
  GitHub: https://github.com/7Ese
  Email: mailto:hi@wayne.im
  Telegram: https://wayne.im/#
  Twitter: https://x.com/0x7Ese
